CREATE TABLE books(
BookID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
BookName varchar(100) NOT NULL ,
BookPrice NUMBER NOT NULL,
TotalQuantatity NUMBER NOT NULL,
PRIMARY KEY (BookID)
);
------------------------------------------------------------------------
CREATE TABLE BOOK_DETAILS(
BookID NUMBER UNIQUE,
describtion varchar(100) NOT NULL,
issue_date DATE NOT NULL,
expiry_data DATE NOT NULL,
CONSTRAINT FR_BookID_cons  FOREIGN KEY (BookID) REFERENCES Books(BookID)
);
----------------------------------------------------------------------------
ALTER TABLE BOOK_DETAILS 
MODIFY BOOKID NUMBER NOT NULL;
--------------------------------------------------------------------------
INSERT INTO BOOK_DETAILS (BOOKID, DESCRIPTION, ISSUE_DATE, EXPIRY_DATA)
VALUES (10,'The first book in the epic fantasy series.', TO_DATE('1996-08-06', 'YYYY-MM-DD'), TO_DATE('2030-12-31', 'YYYY-MM-DD'));


INSERT INTO HR.BOOK_DETAILS (BOOKID, DESCRIPTION, ISSUE_DATE, EXPIRY_DATA)  
VALUES (15, 'A teenager''s journey through alienation and angst.',  
        TO_DATE('1996-08-06', 'YYYY-MM-DD'),  
        TO_DATE('2030-12-31', 'YYYY-MM-DD'));  

INSERT INTO HR.BOOK_DETAILS (BOOKID, DESCRIPTION, ISSUE_DATE, EXPIRY_DATA)  
VALUES (16	,'A psychological novel exploring guilt and justice.',  
        TO_DATE('1951-07-16', 'YYYY-MM-DD'),  
        TO_DATE('2030-12-31', 'YYYY-MM-DD'));  

  
INSERT INTO HR.BOOK_DETAILS (BOOKID, DESCRIPTION, ISSUE_DATE, EXPIRY_DATA)  
VALUES (2	,'	A poetic journey through love and loss.',  
        TO_DATE('2020-05-15', 'YYYY-MM-DD'),  
        TO_DATE('2030-12-31', 'YYYY-MM-DD')); 


INSERT INTO HR.BOOK_DETAILS (BOOKID, DESCRIPTION, ISSUE_DATE, EXPIRY_DATA)  
VALUES (3,'	A tale of adventure and self-discovery.',  
        TO_DATE('2018-09-10', 'YYYY-MM-DD'),  
        TO_DATE('2030-12-31', 'YYYY-MM-DD')); 


INSERT INTO HR.BOOK_DETAILS (BOOKID, DESCRIPTION, ISSUE_DATE, EXPIRY_DATA)  
VALUES (4	,'	A mysterious journey to uncover hidden truths.',  
        TO_DATE('2017-11-21', 'YYYY-MM-DD'),  
        TO_DATE('2030-12-31', 'YYYY-MM-DD')); 

INSERT INTO HR.BOOK_DETAILS (BOOKID, DESCRIPTION, ISSUE_DATE, EXPIRY_DATA)  
VALUES (5	,'A classic novel about wealth, love, and dreams.',  
        TO_DATE('1925-04-10', 'YYYY-MM-DD'),  
        TO_DATE('2030-12-31', 'YYYY-MM-DD')); 


INSERT INTO HR.BOOK_DETAILS (BOOKID, DESCRIPTION, ISSUE_DATE, EXPIRY_DATA)  
VALUES (6	,'A story of racial injustice and childhood.',  
        TO_DATE('1960-07-11', 'YYYY-MM-DD'),  
        TO_DATE('2030-12-31', 'YYYY-MM-DD')); 


INSERT INTO HR.BOOK_DETAILS (BOOKID, DESCRIPTION, ISSUE_DATE, EXPIRY_DATA)  
VALUES (7	,'A dystopian novel about totalitarian control.',  
        TO_DATE('1949-06-08', 'YYYY-MM-DD'),  
        TO_DATE('2030-12-31', 'YYYY-MM-DD')); 

INSERT INTO HR.BOOK_DETAILS (BOOKID, DESCRIPTION, ISSUE_DATE, EXPIRY_DATA)  
VALUES (8	,'A witty romance novel about love and class.',  
        TO_DATE('1813-01-28', 'YYYY-MM-DD'),  
        TO_DATE('2030-12-31', 'YYYY-MM-DD')); 

INSERT INTO HR.BOOK_DETAILS (BOOKID, DESCRIPTION, ISSUE_DATE, EXPIRY_DATA)  
VALUES (9	,'A fantastical adventure of a hobbit’s journey.',  
        TO_DATE('1937-09-21', 'YYYY-MM-DD'),  
        TO_DATE('2030-12-31', 'YYYY-MM-DD')); 

--------------------------------------------------------------------------------------------------------------------
ALTER TABLE BOOK_DETAILS RENAME COLUMN EXPIRY_DATA TO EXPIRY_DATE;
-------------------------------------------------------------------------------------------
ALTER TABLE BOOK_DETAILS DROP CONSTRAINT FR_BookID_cons;
-------------------------------------------------------------------------------------------
ALTER TABLE BOOK_DETAILS 
ADD CONSTRAINT fk_bookid 
FOREIGN KEY (BookID)
REFERENCES BOOKS(BookID)
ON DELETE CASCADE;

------------------------------------------------------------------------------------------

INSERT INTO BOOKS VALUES (1,'Moby-Dick',14.99,30);


SELECT *FROM
BOOKS	B LEFT OUTER JOIN  BOOK_DETAILS BD
ON B.BOOKID =BD.BOOKID ;


INSERT INTO BOOKS VALUES (11,'Harry Potter and the Sorcerer’s Stone',16.99,6);




SELECT *
FROM BOOKS B  
INNER JOIN BOOK_DETAILS BD  
ON B.BOOKID = BD.BOOKID  
WHERE B.BOOKID = 5;

SELECT * FROM BOOK_DETAILS WHERE BookID = 1

 

CREATE TABLE users (

id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
f_name varchar(50)NOT NULL,
l_name varchar(50)NOT NULL,
e_mail varchar(50)NOT NULL UNIQUE ,
pass varchar(50)NOT NULL

);



INSERT INTO USERS(F_NAME,L_NAME,E_MAIL,PASS) VALUES('amar','hani','amar@gmail.com','123');

SELECT E_MAIL,PASS FROM USERS
      		
SELECT E_MAIL, PASS FROM USERS WHERE E_MAIL= 'ahmed@gmail.com' AND PASS='Ah123?'